version: '3.7'
services:

  nginx:
    image: nginx:1.17-alpine
    container_name: lrv9-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - moveek_docker_client

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lrv9-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - moveek_docker_client

  db_test:
    image: mysql:8.0-oracle
    container_name: lrv9-db-test
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'moveek-client-db'
      MYSQL_USER: 'moveekclient'
      MYSQL_PASSWORD: 'moveekclient'
    volumes:
      - .docker-compose/mysql/conf/my.cnf:/etc/mysql/conf.d/docker.cnf

networks:
  moveek_docker_client:
    external: true
